Add common commands
getporter/docker-compose-mixin pull request #49
Opened 2024-09-05 14:40 UTC by eugencowie

### What does this change?

Initial design and structure for adding docker-compose commands as first-class fields. This PR includes pull/up/down as proof of concept, but this can easily be extended to other commands in a follow-on PR.

Currently these commands use the same syntax as the existing `docker-compose` field for defining arguments and flags, which is quite flexible as it doesn't constrain the user to a specific set of predefined options. For example:

```yaml
docker-compose:
  description: Pull services
  flags:
    file: compose.yml
  pull:
    arguments:
      - serviceA
      - serviceB
    flags:
      ignore-pull-failures:
```

This is equivalent to `docker-compose --file compose.yml pull --ignore-pull-failures serviceA serviceB`.

However, custom fields for each command could be added in the future without breaking backwards compatibility, allowing for a more consise and natural syntax as suggested in https://github.com/getporter/docker-compose-mixin/issues/3#issuecomment-886222995

### What issue does it fix?

Partially implements #3, though more work is needed to flesh it out.

### Notes for the reviewer

This is not a breaking change, the existing mixin syntax can still be used and works as expected.

I've updated the tests and examples to use the new syntax.

2024-09-27 18:58 UTC, kichristensen requested changes
Thanks for the PR, I will take a close look soon. But I have added a few small commets

2024-09-27 18:58 UTC, kichristensen commented on README.md
> +This is equivilent to: `docker-compose --file compose.yml pull --ignore-pull-failures --policy missing serviceA serviceB`
```suggestion
This is equivalent to: `docker-compose --file compose.yml pull --ignore-pull-failures --policy missing serviceA serviceB`
```

2024-09-27 18:58 UTC, kichristensen commented on README.md
> +This is equivilent to: `docker-compose up --detach --timeout 30 serviceA serviceB`
```suggestion
This is equivalent to: `docker-compose up --detach --timeout 30 serviceA serviceB`
```

2024-09-27 18:58 UTC, kichristensen commented on README.md
> +This is equivilent to: `docker-compose down --remove-orphans --timeout 30`
```suggestion
This is equivalent to: `docker-compose down --remove-orphans --timeout 30`
```

2024-09-30 15:48 UTC, sgettys commented
We should probably be doing the compose pull during build instead of action runtime so that all of the image dependencies are built into the porter bundle. I know this requires DinD so I need to see if it expects the images to be in the host systems docker cache or if it can use the bundle images docker cache to see if it would even honor pulling images at build time

2024-09-30 16:04 UTC, eugencowie commented
> We should probably be doing the compose pull during build instead of action runtime so that all of the image dependencies are built into the porter bundle. I know this requires DinD so I need to see if it expects the images to be in the host systems docker cache or if it can use the bundle images docker cache to see if it would even honor pulling images at build time

Would that be resolved by #26?

2024-10-01 15:01 UTC, sgettys commented
> > We should probably be doing the compose pull during build instead of action runtime so that all of the image dependencies are built into the porter bundle. I know this requires DinD so I need to see if it expects the images to be in the host systems docker cache or if it can use the bundle images docker cache to see if it would even honor pulling images at build time
> 
> Would that be resolved by #26?

I think partially although the docker-compose mixin build should be collecting those image at bundle build time and it's not. That's a secondary issue that we should also be addressing. I think this PR is good for now but I'm going to open an issue specifically for the build as running a "docker compose pull" at bundle runtime kind of defeats the purpose of CNAB.

2024-10-01 18:53 UTC, kichristensen approved these changes

2024-10-01 18:53 UTC, merged